PHASE3_DOC_SNAPSHOT_DATE = "2026-04-25"

API_CONFIG_MANAGER_GETTER_INVENTORY = ()

SERVICE_CORE_CONFIG_MANAGER_COMPAT_INVENTORY = ()

PHASE3_CONFIG_MANAGER_INVENTORY_HINTS = (
    *API_CONFIG_MANAGER_GETTER_INVENTORY,
    *SERVICE_CORE_CONFIG_MANAGER_COMPAT_INVENTORY,
)
